version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20

  pre_build:
    commands:
      - echo "npm install"
      - cd Frontend
      - npm install
      - cd ..

  build:
    commands:
      - echo "Build frontend"
      - cd Frontend
      - npm run build
      - cd ..
      - echo "Build backend"
      - cd Backend/bookapp
      - chmod +x gradlew
      - ./gradlew clean build
      - cd ../..
      - echo "Build completed on $(date)"

artifacts:
  files:
    - Frontend/dist/**/*
    - Backend/bookapp/build/libs/*.jar
#codedeploy설정    - appspec.yml
#scripts배포 스크립트    - scripts/**/*
