version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - echo "Install frontend dependencies"
      - cd Frontend
      - npm install

  build:
    commands:
      - echo "Build frontend"
      - npm run build
      - echo "Frontend build completed on $(date)"

artifacts:
  base-directory: Frontend/dist
  files:
    - "**/*"

