# 서버 설정
server:
  port: 8080
  tomcat:
    max-http-form-post-size: 50MB
    max-swallow-size: 50MB

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

# 애플리케이션 설정
spring:
  application:
    name: bookapp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    group:
      default: "secret"
  h2:
    console:
      enabled: true
      path: /h2-console

  # 데이터베이스 초기화 및 data.sql 동기화 옵션
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
